//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Atenea
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grupo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Grupo()
        {
            this.Horario = new HashSet<Horario>();
        }
    
        public int ID_Grupo { get; set; }
        public string Aula { get; set; }
        public string Ced_Profesor { get; set; }
        public int ID_Horario { get; set; }
        public string Ced_Alumno { get; set; }
        public int ID_Matricula { get; set; }
    
        public virtual Alumno Alumno { get; set; }
        public virtual Docente Docente { get; set; }
        public virtual Matricula Matricula { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Horario> Horario { get; set; }
    }
}
